# rename this file to settings.yaml and enter the api keys for poloniex
polo_api:
  key: R2ECOFGH-Q37RQGEK-BBQQOF5L-DXME126J
  secret: 64dda88cf14f4c3ba016049aab64158104e5ba3b9e748a27e4c812c8e09323468badadd970923895d81c4cd636ed097e7be23b893aac53b2c0f9c08f28b1112a


# set my coin data
coin:
  currency: BTC
  my_coin: ZEC

# dust definitions
# Those variables should be adjusted for the coin. They may change as the volume and value of the coin changes.

# This is total BTC amount of the orders in the orderbook
dust_total: 5.5

# this is the order amount in coins to accept not dust
dust_amount: 50.0

# the spread that we like to trade
min_spread: 0.0002

# How much coin we may trade?
max_trading_amount: 3
